// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqBiKSbo98xMThZZwp2Z85ghMp7QUCgeM',
    appId: '1:17129356765:web:01b3f2fb6cbd90c4a00a34',
    messagingSenderId: '17129356765',
    projectId: 'wellness-tracker-app-d8def',
    authDomain: 'wellness-tracker-app-d8def.firebaseapp.com',
    storageBucket: 'wellness-tracker-app-d8def.firebasestorage.app',
    measurementId: 'G-873WFRS0PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYN9FAZyDj5mmAQ_qXmkrQz1lmOL7-W0o',
    appId: '1:17129356765:android:666d0903c4f85620a00a34',
    messagingSenderId: '17129356765',
    projectId: 'wellness-tracker-app-d8def',
    storageBucket: 'wellness-tracker-app-d8def.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbSas3R55LcvSQraTz-oYcd_PL2EL4DeI',
    appId: '1:17129356765:ios:0313aa1ba2d760caa00a34',
    messagingSenderId: '17129356765',
    projectId: 'wellness-tracker-app-d8def',
    storageBucket: 'wellness-tracker-app-d8def.firebasestorage.app',
    iosBundleId: 'com.example.wellnesstrackerapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbSas3R55LcvSQraTz-oYcd_PL2EL4DeI',
    appId: '1:17129356765:ios:0313aa1ba2d760caa00a34',
    messagingSenderId: '17129356765',
    projectId: 'wellness-tracker-app-d8def',
    storageBucket: 'wellness-tracker-app-d8def.firebasestorage.app',
    iosBundleId: 'com.example.wellnesstrackerapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqBiKSbo98xMThZZwp2Z85ghMp7QUCgeM',
    appId: '1:17129356765:web:143d99b47d237836a00a34',
    messagingSenderId: '17129356765',
    projectId: 'wellness-tracker-app-d8def',
    authDomain: 'wellness-tracker-app-d8def.firebaseapp.com',
    storageBucket: 'wellness-tracker-app-d8def.firebasestorage.app',
    measurementId: 'G-5MGPMWQCSY',
  );
}
